const images: { [key: string]: any } = {
  'aufgabe_21': require('../../../../packages/shared/assets/img/aufgabe_21.png'),
  'aufgabe_55': require('../../../../packages/shared/assets/img/aufgabe_55.jpg'),
  'aufgabe_130': require('../../../../packages/shared/assets/img/aufgabe_130.jpg'),
  'aufgabe_176': require('../../../../packages/shared/assets/img/aufgabe_176.png'),
  'aufgabe_187': require('../../../../packages/shared/assets/img/aufgabe_187.jpg'),
  'aufgabe_226': require('../../../../packages/shared/assets/img/aufgabe_226.png'),
  'baden-wurttemberg_1': require('../../../../packages/shared/assets/img/baden-wurttemberg_1.png'),
  'baden-wurttemberg_8': require('../../../../packages/shared/assets/img/baden-wurttemberg_8.png'),
  'bayern_1': require('../../../../packages/shared/assets/img/bayern_1.png'),
  'bayern_8': require('../../../../packages/shared/assets/img/bayern_8.png'),
  'berlin_1': require('../../../../packages/shared/assets/img/berlin_1.png'),
  'berlin_8': require('../../../../packages/shared/assets/img/berlin_8.png'),
  'brandenburg_aufgabe_1': require('../../../../packages/shared/assets/img/brandenburg_aufgabe_1.png'),
  'brandenburg_aufgabe_8': require('../../../../packages/shared/assets/img/brandenburg_aufgabe_8.png'),
  'bremen_1': require('../../../../packages/shared/assets/img/bremen_1.png'),
  'bremen_8': require('../../../../packages/shared/assets/img/bremen_8.png'),
  'hamburg_1': require('../../../../packages/shared/assets/img/hamburg_1.png'),
  'hamburg_8': require('../../../../packages/shared/assets/img/hamburg_8.png'),
  'hessen_1': require('../../../../packages/shared/assets/img/hessen_1.png'),
  'hessen_8': require('../../../../packages/shared/assets/img/hessen_8.png'),
  'mecklenburg-vorpommern_1': require('../../../../packages/shared/assets/img/mecklenburg-vorpommern_1.png'),
  'mecklenburg-vorpommern_8': require('../../../../packages/shared/assets/img/mecklenburg-vorpommern_8.png'),
  'niedersachsen_1': require('../../../../packages/shared/assets/img/niedersachsen_1.png'),
  'niedersachsen_8': require('../../../../packages/shared/assets/img/niedersachsen_8.png'),
  'nordrhein-westfalen_1': require('../../../../packages/shared/assets/img/nordrhein-westfalen_1.png'),
  'nordrhein-westfalen_8': require('../../../../packages/shared/assets/img/nordrhein-westfalen_8.png'),
  'rheinland-pfalz_1': require('../../../../packages/shared/assets/img/rheinland-pfalz_1.png'),
  'rheinland-pfalz_8': require('../../../../packages/shared/assets/img/rheinland-pfalz_8.png'),
  'saarland_1': require('../../../../packages/shared/assets/img/saarland_1.png'),
  'saarland_8': require('../../../../packages/shared/assets/img/saarland_8.png'),
  'sachsen_1': require('../../../../packages/shared/assets/img/sachsen_1.png'),
  'sachsen_8': require('../../../../packages/shared/assets/img/sachsen_8.png'),
  'sachsen-anhalt_1': require('../../../../packages/shared/assets/img/sachsen-anhalt_1.png'),
  'sachsen-anhalt_8': require('../../../../packages/shared/assets/img/sachsen-anhalt_8.png'),
  'schleswig-holstein_1': require('../../../../packages/shared/assets/img/schleswig-holstein_1.png'),
  'schleswig-holstein_8': require('../../../../packages/shared/assets/img/schleswig-holstein_8.png'),
  'thuringen_1': require('../../../../packages/shared/assets/img/thuringen_1.png'),
  'thuringen_8': require('../../../../packages/shared/assets/img/thuringen_8.png'),
};

export default images; 